### ISSUE TITLE
Website Down.

### ISSUE THREAD

**Issue by Genious28** [Myphz/sortvisualizer#3]
![image](https://user-images.githubusercontent.com/97228026/160428213-d895ff33-d000-476b-9ff0-0716fe88bed1.png)

**Comment by Genious28** [comment]
Try this;
https://docs.github.com/en/pages

**Comment by Myphz** [comment]
Thanks for your report! 
The website will be up again tomorrow. 
Sorry for the inconvenience.

**Comment by Myphz** [comment]
The website is back up, thanks for your assistance
